theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

# the base hostname & protocol for your site, e.g. http://example.com
url: 'https://akman.github.io' 

# the subpath of your site, e.g. /blog
baseurl: '/java-boilerplate-gradle'

title: Java Boilerplate Project Documentation

# it will appear in your document head meta and in your feed.xml
description: >-
  Java Boilerplate Project Site.
  Documentation.

twitter_username: Kapitman

github_username: Akman

email: akman.ru@gmail.com
